CREATE DATABASE TELEPHONIE;
CREATE USER ETU with password '1234';
GRANT CONNECT ON DATABASE  TELEPHONIE TO ETU;
ALTER DATABASE TELEPHONIE OWNER TO ETU;
CREATE ROLE EtuRole;
ALTER ROLE EtuRole SUPERUSER;
GRANT EtuRole TO ETU;

psql -U etu -d telephonie
-------------------------DROP---------------------
DROP table Token CASCADe
--------------------------------------------SEQUENCE---------------------------------
CREATE SEQUENCE IF NOT EXISTS user_seq START 1;
CREATE SEQUENCE IF NOT EXISTS money_seq START 10;
CREATE SEQUENCE IF NOT EXISTS user_seq START 1;
---------------------------------------------POSTGRES------------------------------
CREATE VIEW MONEYNONVALIDE as 
	SELECT m.ID_MOUVEMENT,u.ID_UTILISATEUR,m.TYPES,u.TELEPHONE,m.DATE_TRANSACTION,m.MONTANT,m.ETAT
	FROM UTILISATEUR u join MONEY_MOUVEMENT m on u.ID_UTILISATEUR =m.ID_UTILISATEUR 
	where m.TYPES=1 and etat=0;
CREATE TABLE UTILISATEUR 
(
	ID_UTILISATEUR INT PRIMARY KEY,
	NOM VARCHAR(30),
	PRENOM VARCHAR(30),
	LOGIN VARCHAR(30),
	TELEPHONE VARCHAR(15),
	MDP VARCHAR(100),
	Types varchar(30)
);
CREATE TABLE IF NOT EXISTS Token(
	ID_TOKEN varchar(150) PRIMARY KEY,
	ID_UTILISATEUR int,
	DATE_EXPIRATION timestamp,
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS Offre(
	ID_OFFRE int  PRIMARY KEY,
	NOM_OFFRE varchar(50),
	DATE_OFFRE date,
	VALIDITE int,
	prix double
);
CREATE TABLE IF NOT EXISTS TAUX_OFFRE
(
	ID_TAUX INT,
	ID_OFFRE INT,
	VALEUR DOUBLE precision,
	SPECIFICATION VARCHAR(30),
	FOREIGN KEY (ID_OFFRE) REFERENCES Offre(ID_OFFRE)
);
CREATE TABLE IF NOT EXISTS OFFRE_MOUVEMENT(
	ID_MOUVEMENT int  PRIMARY KEY,
	ID_OFFRE int,
	VALEUR_OFFRE double precision,
	ID_UTILISATEUR int,
	TYPE_MOUVEMENT int,
	DATE_MOUVEMENT timestamp,
	FOREIGN KEY (ID_OFFRE) REFERENCES Offre(ID_OFFRE),
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

--OFFRE VALIDE
CREATE OR REPLACE VIEW OFFRE_VALIDE AS SELECT OFFRE_MOUVEMENT.* 
FROM OFFRE,OFFRE_MOUVEMENT 
WHERE OFFRE_MOUVEMENT.ID_OFFRE=OFFRE.ID_OFFRE 
AND (OFFRE_MOUVEMENT.DATE_MOUVEMENT::timestamp+ OFFRE.VALIDITE*interval '24 HOUR')>=NOW();
=1(
--STATISTIQUES
--OFFRE LE PLSU ACHETER
SELECT sum(VALEUR_OFFRE),idoffre from OFFRE_MOUVEMENT group by ID_OFFRE;
--VALEUR OFFRE JOUR
CREATE OR REPLACE VIEW STATISTIQUE_OFFRE_JOUR AS select
    date_trunc('DAY', OFFRE_MOUVEMENT.DATE_MOUVEMENT::timestamp) as DATES,
    SUM(OFFRE_MOUVEMENT.VALEUR_OFFRE) as VALEUR,
    OFFRE.ID_OFFRE,
	OFFRE.NOM_OFFRE
	FROM OFFRE_MOUVEMENT,OFFRE
	WHERE 
	OFFRE_MOUVEMENT.ID_OFFRE=OFFRE.ID_OFFRE
	AND OFFRE_MOUVEMENT.TYPE_MOUVEMENT=1
	group by 1,OFFRE.ID_OFFRE;

---------------------------------------------------
select date_trunc('DAY', OFFRE_MOUVEMENT.DATE_MOUVEMENT::timestamp) as DATES,
    SUM(OFFRE_MOUVEMENT.VALEUR_OFFRE) as VALEUR
	FROM OFFRE_MOUVEMENT,OFFRE
	WHERE 
	OFFRE_MOUVEMENT.ID_OFFRE=OFFRE.ID_OFFRE
	AND OFFRE_MOUVEMENT.TYPE_MOUVEMENT=1
	group by 1;
---------------------------------------------------

--VALEUR OFFRE SEMAINE
CREATE OR REPLACE VIEW STATISTIQUE_OFFRE_SEMAINE AS select
    date_trunc('week', OFFRE_MOUVEMENT.DATE_MOUVEMENT::timestamp) as DATES,
    SUM(OFFRE_MOUVEMENT.VALEUR_OFFRE) as VALEUR,
    OFFRE.ID_OFFRE,
    OFFRE.NOM_OFFRE
from OFFRE_MOUVEMENT,OFFRE
WHERE 
OFFRE_MOUVEMENT.ID_OFFRE=OFFRE.ID_OFFRE
AND OFFRE_MOUVEMENT.TYPE_MOUVEMENT=1
group by 1,OFFRE.ID_OFFRE;


--VALEUR OFFRE MOIS
CREATE OR REPLACE VIEW STATISTIQUE_OFFRE_MOIS AS select
    date_trunc('month', OFFRE_MOUVEMENT.DATE_MOUVEMENT::timestamp) as DATES,
    SUM(OFFRE_MOUVEMENT.VALEUR_OFFRE) as VALEUR,
    OFFRE.ID_OFFRE,
    OFFRE.NOM_OFFRE
from OFFRE_MOUVEMENT,OFFRE
WHERE 
OFFRE_MOUVEMENT.ID_OFFRE=OFFRE.ID_OFFRE
AND OFFRE_MOUVEMENT.TYPE_MOUVEMENT=1
group by 1,OFFRE.ID_OFFRE;


CREATE TABLE IF NOT EXISTS AchatOffre(
	ID_ACHAT int  PRIMARY KEY,
	ID_OFFRE int,
	ID_UTILISATEUR int,
	TYPES_ACHAT varchar(50),
	DATE_ACHAT datetime,
	FOREIGN KEY (ID_OFFRE) REFERENCES Offre(ID_OFFRE),
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS MONEY_MOUVEMENT(
	ID_MOUVEMENT int PRIMARY KEY,
	ID_UTILISATEUR int,
	TYPES int,
	MONTANT double precision,
	DATE_TRANSACTION timestamp,
	ETAT int,
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS CREDIT(
	ID_CREDIT int ,
	CODE varchar(15) unique,
	DATE_EXPIRATION date
);
--MOBILE MONEY
CREATE TABLE IF NOT EXISTS MONEY_MOUVEMENT(
	ID_MOUVEMENT int PRIMARY KEY,
	ID_UTILISATEUR int,
	TYPES int,
	MONTANT double precision,
	DATE_TRANSACTION timestamp,
	ETAT int,
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE IF NOT EXISTS CREDIT_MOUVEMENT(
	ID_CREDIT int,
	ID_UTILISATEUR int,
	TYPES varchar(30),
	MONTANT double,
	DATE_MOUVEMENT datetime
);
CREATE TABLE IF NOT EXISTS APPEL(
	ID_APPEL int,
	TYPES varchar(20),
	NUMERO1 varchar(15),
	NUMERO2 varchar(15),
	DUREE int,
	DATE_APPEL datetime
);