CREATE DATABASE TELEPHONIE;
CREATE USER ETU with password '1234';
GRANT CONNECT ON DATABASE  TELEPHONIE TO ETU;
ALTER DATABASE TELEPHONIE OWNER TO ETU;
CREATE ROLE EtuRole;
ALTER ROLE EtuRole SUPERUSER;
GRANT EtuRole TO ETU;

psql -U etu -d telephonie
-------------------------DROP---------------------
DROP table Token CASCADe
--------------------------------------------SEQUENCE---------------------------------
CREATE SEQUENCE IF NOT EXISTS user_seq START 1;
CREATE SEQUENCE IF NOT EXISTS money_seq START 10;
CREATE SEQUENCE IF NOT EXISTS user_seq START 1;
CREATE SEQUENCE IF NOT EXISTS admin_seq START 1;
---------------------------------------------POSTGRES------------------------------
CREATE VIEW MONEYNONVALIDE as SELECT m.ID_MOUVEMENT,u.ID_UTILISATEUR,m.TYPES,u.TELEPHONE,m.DATE_TRANSACTION,m.MONTANT,m.ETAT FROM UTILISATEUR u join MONEY_MOUVEMENT m on u.ID_UTILISATEUR =m.ID_UTILISATEUR where m.TYPES=1 and etat=0;
CREATE TABLE UserAdmin(
	ID_ADMIN int PRIMARY KEY,
	LOGIN VARCHAR(30),
	MDP varchar(100)
);
CREATE TABLE UTILISATEUR 
(
	ID_UTILISATEUR INT PRIMARY KEY,
	NOM VARCHAR(30),
	PRENOM VARCHAR(30),
	LOGIN VARCHAR(30),
	TELEPHONE VARCHAR(15),
	MDP VARCHAR(100),
	Types varchar(30)
);
CREATE TABLE IF NOT EXISTS Token(
	ID_TOKEN varchar(150) PRIMARY KEY,
	ID_UTILISATEUR int,
	DATE_EXPIRATION timestamp,
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS Offre(
	ID_OFFRE int  PRIMARY KEY,
	NOM_OFFRE varchar(50),
	DATE_OFFRE date,
	VALIDITE int,
	prix double
);
CREATE TABLE IF NOT EXISTS AchatOffre(
	ID_ACHAT int  PRIMARY KEY,
	ID_OFFRE int,
	ID_UTILISATEUR int,
	TYPES_ACHAT varchar(50),
	DATE_ACHAT datetime,
	FOREIGN KEY (ID_OFFRE) REFERENCES Offre(ID_OFFRE),
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS MONEY_MOUVEMENT(
	ID_MOUVEMENT int PRIMARY KEY,
	ID_UTILISATEUR int,
	TYPES int,
	MONTANT double precision,
	DATE_TRANSACTION timestamp,
	ETAT int,
	FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
CREATE TABLE IF NOT EXISTS CREDIT(
	ID_CREDIT int ,
	CODE varchar(15) unique,
	DATE_EXPIRATION date
);
CREATE TABLE IF NOT EXISTS CREDIT_MOUVEMENT(
	ID_CREDIT int,
	ID_UTILISATEUR int,
	TYPES varchar(30),
	MONTANT double,
	DATE_MOUVEMENT datetime
);
CREATE TABLE IF NOT EXISTS APPEL(
	ID_APPEL int,
	TYPES varchar(20),
	NUMERO1 varchar(15),
	NUMERO2 varchar(15),
	DUREE int,
	DATE_APPEL datetime
);